spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boostauth??autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: boostauth

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: ./logs/boostauth.log

boostauth:
  profile: development
  admin:
    username: admin
    password: adminDevPassword
  security: 9t]id,s}WD#ZslGnNsy8ej[lr#6bzgG3