server:
  port: 9000
spring:
  config:
    import: application-@spring.active@.yml
  jpa:
    database: mysql
    #    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path=/swagger-ui.html