spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boostauth
    username: root
    password: root
  thymeleaf:
    cache: false

#logging:
#  file:
#    name: ./logs/boostauth.log

boostauth:
  profile: local
  admin:
    username: admin
    password: admin
  security: security