spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boostauth??autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: boostauth

webserver:
  url: http://localhost:8080

socketserver:
  url: http://localhost:9010