spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/boostauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: boostauthadmin
    password: boostauthadminpwd

logging:
  file:
    name: ./logs/boostauth.log

boostauth:
  profile: production
  admin:
    username: admin
    password: SpUI;zb]bZ1<Kswd^.tjP9;Tr&8sKrbKRQ]9J+f}s#YLeP{NiL$T[4..F1D9wQJh
  security: 6F*PZ6=AafLveRGPkKF}ClS%dCK)C=G0jPB#W;UNHk.JH^4#Mut?XFDk]nGS16H^
