server:
  port: 9000
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import: application-@spring.active@.yml
  jpa:
    database: mysql
    #    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path=/swagger-ui.html

email:
  smtp:
    host: your-host-domain
    port: 465
    auth: true
    ssl:
      enable: true
      protocols: TLSv1.2
    starttls:
      enable: true

application:
  name: BoostAuth
  version: 0.1.0