server:
  port: 9000
spring:
  config:
    import: application-@spring.active@.yml
  jpa:
    database: mysql
    #    show-sql: true
    hibernate:
      ddl-auto: update

email:
  smtp:
    host: your-host-domain
    port: 465
    auth: true
    ssl:
      enable: true
      protocols: TLSv1.2
    starttls:
      enable: true


springdoc:
  swagger-ui:
    path=/swagger-ui.html