spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boostauth
    username: root
    password: root

#logging:
#  file:
#    path: ./logs
#    name: boostauth.log

webserver:
  url: http://localhost:8080

socketserver:
  url: http://localhost:9010