spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/boostauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: boostauthadmin
    password: boostauthadminpwd

logging:
  file:
    path: ./logs
    name: boostauth.log

webserver:
  url: http://web-service:8080

socketserver:
  url: http://web-socket:9010